apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: input-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: local-storage
  volumeName: input-pv

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: output-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi
  storageClassName: local-storage
  volumeName: output-pv